# Generated by Django 5.2.4 on 2025-07-15 07:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vitalrecord',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vitalrecord',
            name='diastolic',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='vitalrecord',
            name='heart_rate',
            field=models.PositiveIntegerField(help_text='Beats per minute'),
        ),
        migrations.AlterField(
            model_name='vitalrecord',
            name='systolic',
            field=models.IntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='vitalrecord',
            name='temperature',
            field=models.DecimalField(decimal_places=1, help_text='In Celsius', max_digits=4),
        ),
    ]
