# Generated by Django 5.2.4 on 2025-07-17 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_patient_address_alter_patient_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B-'), ('AB+', 'AB-'), ('O+', 'O-')], max_length=3),
        ),
        migrations.AddField(
            model_name='vitalrecord',
            name='sugar_level',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Blood sugar level in mg/dL', max_digits=5, null=True),
        ),
    ]
